import io
import re
from docx import Document
from docx.shared import Pt, RGBColor

class DocxService:
    """Service class utilizing python-docx to generate styled Word documents from marketing content copy."""

    @classmethod
    def generate_docx(cls, content):
        """Generates a DOCX file from a Content model record and returns it as a BytesIO stream.
        
        Args:
            content (Content): The database content model instance.
            
        Returns:
            BytesIO: Binary stream of compiled DOCX.
        """
        doc = Document()
        
        # Style configurations
        title = doc.add_paragraph()
        title_run = title.add_run(content.title)
        title_run.font.name = 'Arial'
        title_run.font.size = Pt(20)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(30, 41, 59) # Slate 800
        
        # Add basic metadata
        meta = doc.add_paragraph()
        meta_run = meta.add_run(f"Generated by Oplyra | Workspace: {content.project.name}\n")
        meta_run.font.italic = True
        meta_run.font.size = Pt(9)
        meta_run.font.color.rgb = RGBColor(100, 116, 139) # Slate 500
        
        lines = content.body.split('\n')
        for line in lines:
            line_str = line.strip()
            if not line_str:
                doc.add_paragraph() # Add empty paragraph for spacing
                continue
                
            # Parse headings
            if line_str.startswith('# '):
                h = doc.add_paragraph()
                run = h.add_run(line_str.replace('# ', '', 1))
                run.font.name = 'Arial'
                run.font.size = Pt(16)
                run.font.bold = True
                run.font.color.rgb = RGBColor(79, 70, 229) # Indigo 600
                
            elif line_str.startswith('## '):
                h = doc.add_paragraph()
                run = h.add_run(line_str.replace('## ', '', 1))
                run.font.name = 'Arial'
                run.font.size = Pt(14)
                run.font.bold = True
                run.font.color.rgb = RGBColor(51, 65, 85) # Slate 700
                
            elif line_str.startswith('### '):
                h = doc.add_paragraph()
                run = h.add_run(line_str.replace('### ', '', 1))
                run.font.name = 'Arial'
                run.font.size = Pt(12)
                run.font.bold = True
                run.font.color.rgb = RGBColor(71, 85, 105) # Slate 600
                
            # Lists
            elif line_str.startswith('- ') or line_str.startswith('* '):
                p = doc.add_paragraph(style='List Bullet')
                text = line_str.replace('- ', '', 1).replace('* ', '', 1).strip()
                cls._add_formatted_text(p, text)
                
            elif re.match(r'^\d+\.\s+', line_str):
                p = doc.add_paragraph(style='List Number')
                num_match = re.match(r'^(\d+\.\s+)', line_str)
                prefix = num_match.group(1)
                text = line_str.replace(prefix, '', 1).strip()
                cls._add_formatted_text(p, text)
                
            else:
                p = doc.add_paragraph()
                cls._add_formatted_text(p, line_str)
                
        stream = io.BytesIO()
        doc.save(stream)
        stream.seek(0)
        return stream

    @classmethod
    def _add_formatted_text(cls, paragraph, text):
        """Parses simple **bold** and *italic* markdown segments and adds them as runs."""
        # Simple tokenization for markdown bold/italic tags
        pattern = re.compile(r'(\*\*.*?\*\*|\*.*?\*)')
        parts = pattern.split(text)
        for part in parts:
            if part.startswith('**') and part.endswith('**'):
                run = paragraph.add_run(part[2:-2])
                run.bold = True
            elif part.startswith('*') and part.endswith('*'):
                run = paragraph.add_run(part[1:-1])
                run.italic = True
            else:
                paragraph.add_run(part)
