from io import BytesIO
import html
import re
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

class PDFService:
    """Service class utilizing ReportLab to generate styled PDF assets from marketing content copy."""

    @staticmethod
    def _draw_header_footer(canvas, doc):
        """Draws consistent headers and footers on every page of the document."""
        canvas.saveState()
        
        # 1. Header (Only on pages > 1 to look cleaner, or on all pages. Let's do all pages since it is short)
        canvas.setFont('Helvetica-Bold', 8)
        canvas.setFillColor(HexColor('#4f46e5'))  # Premium Indigo
        canvas.drawString(54, 750, "Oplyra")
        
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(HexColor('#64748b'))  # Slate grey
        canvas.drawRightString(558, 750, f"Campaign Workspace: {doc.project_name}")
        
        # Header divider line
        canvas.setStrokeColor(HexColor('#e2e8f0'))
        canvas.setLineWidth(0.75)
        canvas.line(54, 742, 558, 742)
        
        # 2. Footer
        # Footer divider line
        canvas.line(54, 60, 558, 60)
        
        canvas.drawString(54, 45, "Generated by Oplyra")
        canvas.drawRightString(558, 45, f"Page {doc.page}")
        
        canvas.restoreState()

    @classmethod
    def generate_pdf(cls, content):
        """Generates a PDF file from a Content model record and returns it as a BytesIO stream.
        
        Args:
            content (Content): The database content model instance.
            
        Returns:
            BytesIO: Binary stream of compiled PDF.
        """
        buffer = BytesIO()
        
        # 1. Setup doc layout template
        # 54pt is 0.75in margins, leaving top margin 72pt (1in) to clear header
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        # Attach custom parameter to document context for canvas drawing callback
        doc.project_name = content.project.name
        
        # 2. Configure sample stylesheet and custom colors
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'PDFTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=HexColor('#1e293b'),
            spaceAfter=20
        )
        
        h1_style = ParagraphStyle(
            'PDFH1',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=15,
            leading=18,
            textColor=HexColor('#4f46e5'),
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )
        
        h2_style = ParagraphStyle(
            'PDFH2',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=15,
            textColor=HexColor('#334155'),
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'PDFBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=15,
            textColor=HexColor('#334155'),
            spaceAfter=10
        )
        
        bullet_style = ParagraphStyle(
            'PDFBullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=HexColor('#334155'),
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=6
        )
        
        blockquote_style = ParagraphStyle(
            'PDFBlockquote',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9.5,
            leading=14,
            textColor=HexColor('#475569')
        )
        
        story = []
        
        # 3. Add Document Title Header
        story.append(Paragraph(html.escape(content.title), title_style))
        story.append(Spacer(1, 10))
        
        # 4. Custom Lightweight Markdown-to-Platypus Flowables parser
        # Split text by lines to parse structure correctly
        lines = content.body.split('\n')
        in_list = False
        
        for line in lines:
            line_str = line.strip()
            if not line_str:
                # Add spacer for empty lines
                story.append(Spacer(1, 6))
                continue
                
            # Escape raw XML symbols to prevent ReportLab compiler crashing
            escaped_text = html.escape(line_str)
            
            # Translate markdown tags: **bold** and *italic*
            escaped_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', escaped_text)
            escaped_text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', escaped_text)
            
            # Check for headings
            if line_str.startswith('# '):
                # We skip standard # Title because we already drew it as main Title flowable
                cleaned = escaped_text.replace('# ', '', 1)
                story.append(Paragraph(cleaned, h1_style))
            elif line_str.startswith('## '):
                cleaned = escaped_text.replace('## ', '', 1)
                story.append(Paragraph(cleaned, h1_style))
            elif line_str.startswith('### '):
                cleaned = escaped_text.replace('### ', '', 1)
                story.append(Paragraph(cleaned, h2_style))
                
            # Check for blockquotes
            elif line_str.startswith('&gt;') or line_str.startswith('>'):
                cleaned = escaped_text.replace('&gt;', '', 1).replace('>', '', 1).strip()
                p_quote = Paragraph(cleaned, blockquote_style)
                
                # Wrap inside a single-cell Table with colored borders to resemble blockquotes
                tbl = Table([[p_quote]], colWidths=[doc.width])
                tbl.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), HexColor('#f8fafc')),
                    ('LEFTPADDING', (0,0), (-1,-1), 12),
                    ('RIGHTPADDING', (0,0), (-1,-1), 12),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('LINELEFT', (0,0), (-1,-1), 3.5, HexColor('#4f46e5')),  # Left border indigo
                ]))
                story.append(Spacer(1, 6))
                story.append(tbl)
                story.append(Spacer(1, 6))
                
            # Check for list items
            elif line_str.startswith('- ') or line_str.startswith('* '):
                cleaned = escaped_text.replace('- ', '', 1).replace('* ', '', 1).strip()
                bullet_bullet = "&bull; "
                story.append(Paragraph(bullet_bullet + cleaned, bullet_style))
                
            # Check for ordered list items
            elif re.match(r'^\d+\.\s+', line_str):
                # Extract number prefix
                num_match = re.match(r'^(\d+\.\s+)', line_str)
                prefix = num_match.group(1)
                cleaned = escaped_text.replace(prefix, '', 1).strip()
                story.append(Paragraph(prefix + cleaned, bullet_style))
                
            # Standard body text
            else:
                story.append(Paragraph(escaped_text, body_style))
                
        # 5. Build document and trigger canvas drawings
        doc.build(
            story,
            onFirstPage=cls._draw_header_footer,
            onLaterPages=cls._draw_header_footer
        )
        
        # Seek stream back to start
        buffer.seek(0)
        return buffer

    @classmethod
    def generate_report_pdf(cls, report):
        """Generates a PDF file from a Report model record and returns it as a BytesIO stream."""
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        # Use project name if available, fallback to "Oplyra"
        doc.project_name = report.project.name if report.project else "Oplyra Client"
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'PDFTitle', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=HexColor('#1e293b'), spaceAfter=20
        )
        h1_style = ParagraphStyle(
            'PDFH1', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=15, leading=18, textColor=HexColor('#4f46e5'), spaceBefore=14, spaceAfter=8, keepWithNext=True
        )
        h2_style = ParagraphStyle(
            'PDFH2', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=12, leading=15, textColor=HexColor('#334155'), spaceBefore=12, spaceAfter=6, keepWithNext=True
        )
        body_style = ParagraphStyle(
            'PDFBody', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=HexColor('#334155'), spaceAfter=8
        )
        blockquote_style = ParagraphStyle(
            'PDFBlockquote', parent=styles['Normal'], fontName='Helvetica-Oblique', fontSize=9.5, leading=13.5, textColor=HexColor('#475569'), leftIndent=10
        )
        bullet_style = ParagraphStyle(
            'PDFBullet', parent=styles['Normal'], fontName='Helvetica', fontSize=10, leading=14, textColor=HexColor('#334155'), leftIndent=15, firstLineIndent=-10, spaceAfter=4
        )
        
        story = []
        
        # Main Title header
        story.append(Paragraph(html.escape(report.title), title_style))
        story.append(Spacer(1, 10))
        
        # Parse markdown lines
        lines = (report.content_markdown or "").split('\n')
        for line in lines:
            line_str = line.strip()
            if not line_str:
                story.append(Spacer(1, 4))
                continue
                
            escaped_text = html.escape(line_str)
            escaped_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', escaped_text)
            escaped_text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', escaped_text)
            
            if line_str.startswith('# '):
                cleaned = escaped_text.replace('# ', '', 1)
                story.append(Paragraph(cleaned, h1_style))
            elif line_str.startswith('## '):
                cleaned = escaped_text.replace('## ', '', 1)
                story.append(Paragraph(cleaned, h1_style))
            elif line_str.startswith('### '):
                cleaned = escaped_text.replace('### ', '', 1)
                story.append(Paragraph(cleaned, h2_style))
            elif line_str.startswith('&gt;') or line_str.startswith('>'):
                cleaned = escaped_text.replace('&gt;', '', 1).replace('>', '', 1).strip()
                p_quote = Paragraph(cleaned, blockquote_style)
                tbl = Table([[p_quote]], colWidths=[doc.width])
                tbl.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), HexColor('#f8fafc')),
                    ('LEFTPADDING', (0,0), (-1,-1), 12),
                    ('RIGHTPADDING', (0,0), (-1,-1), 12),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('LINELEFT', (0,0), (-1,-1), 3.5, HexColor('#4f46e5')),
                ]))
                story.append(Spacer(1, 6))
                story.append(tbl)
                story.append(Spacer(1, 6))
            elif line_str.startswith('- ') or line_str.startswith('* '):
                cleaned = escaped_text.replace('- ', '', 1).replace('* ', '', 1).strip()
                story.append(Paragraph("&bull; " + cleaned, bullet_style))
            elif re.match(r'^\d+\.\s+', line_str):
                num_match = re.match(r'^(\d+\.\s+)', line_str)
                prefix = num_match.group(1)
                cleaned = escaped_text.replace(prefix, '', 1).strip()
                story.append(Paragraph(prefix + cleaned, bullet_style))
            else:
                story.append(Paragraph(escaped_text, body_style))
                
        doc.build(
            story,
            onFirstPage=cls._draw_header_footer,
            onLaterPages=cls._draw_header_footer
        )
        buffer.seek(0)
        return buffer
