"""Permission catalog and default role → permission matrix for Internal Admin."""
from __future__ import annotations

# Canonical permission codes (resource:action)
PERMISSIONS = {
    'admin:all': 'Wildcard — super admin only',
    'dashboard:read': 'View platform dashboard KPIs',
    'users:read': 'Search and view customer users',
    'users:write': 'Edit, suspend, activate customers',
    'users:delete': 'Delete customer accounts',
    'users:reset_password': 'Issue password reset links',
    'users:impersonate': 'Impersonate a customer (super_admin)',
    'users:assign_roles': 'Change org membership roles',
    'billing:read': 'View plans, invoices, revenue',
    'billing:write': 'Refunds, coupons, plan mutations',
    'ai:read': 'AI usage, cost, provider health',
    'ai:write': 'AI provider / limit configuration',
    'campaigns:read': 'View all campaigns and jobs',
    'campaigns:write': 'Retry / cancel campaign automations',
    'support:read': 'View support tickets and timelines',
    'support:write': 'Assign tickets and internal notes',
    'infra:read': 'System health, queues, storage',
    'infra:write': 'Maintenance and infra actions',
    'audit:read': 'View admin and security audit logs',
    'flags:read': 'View feature flags',
    'flags:write': 'Toggle feature flags',
    'settings:read': 'View system settings',
    'settings:write': 'Mutate system settings',
    'admins:manage': 'Manage internal admin users and roles',
}

# Role slug → permission codes
ROLE_MATRIX = {
    'super_admin': ['admin:all'],
    'admin': [
        'dashboard:read',
        'users:read', 'users:write', 'users:reset_password', 'users:assign_roles',
        'billing:read', 'billing:write',
        'ai:read', 'ai:write',
        'campaigns:read', 'campaigns:write',
        'support:read', 'support:write',
        'infra:read', 'infra:write',
        'audit:read',
        'flags:read', 'flags:write',
        'settings:read',
    ],
    'support': [
        'dashboard:read',
        'users:read', 'users:write', 'users:reset_password',
        'campaigns:read',
        'support:read', 'support:write',
        'audit:read',
        'flags:read',
        'settings:read',
    ],
    'finance': [
        'dashboard:read',
        'billing:read', 'billing:write',
        'ai:read',
        'audit:read',
        'settings:read',
    ],
    'operations': [
        'dashboard:read',
        'ai:read', 'ai:write',
        'campaigns:read', 'campaigns:write',
        'infra:read', 'infra:write',
        'audit:read',
        'flags:read', 'flags:write',
        'settings:read',
    ],
    'marketing': [
        'dashboard:read',
        'users:read',
        'campaigns:read', 'campaigns:write',
        'flags:read', 'flags:write',
        'settings:read',
    ],
    'developer': [
        'dashboard:read',
        'ai:read', 'ai:write',
        'infra:read', 'infra:write',
        'audit:read',
        'flags:read',
        'settings:read',
    ],
    'auditor': [
        'dashboard:read',
        'users:read',
        'billing:read',
        'ai:read',
        'campaigns:read',
        'support:read',
        'infra:read',
        'audit:read',
        'flags:read',
        'settings:read',
    ],
}

ROLE_META = {
    'super_admin': ('Super Admin', 'Full platform control including staff management'),
    'admin': ('Admin', 'All modules except super-admin settings and impersonation'),
    'support': ('Support Agent', 'Users and tickets; no billing mutations'),
    'finance': ('Finance', 'Billing and revenue; no user editing'),
    'operations': ('Operations', 'Infrastructure, monitoring, flags'),
    'marketing': ('Marketing', 'Campaigns and growth flags'),
    'developer': ('Developer', 'Logs, health, AI providers'),
    'auditor': ('Read Only Auditor', 'View-only across modules'),
}

# Route endpoint → required permission (module gate)
ROUTE_PERMISSIONS = {
    'platform_admin.overview': 'dashboard:read',
    'platform_admin.users': 'users:read',
    'platform_admin.user_detail': 'users:read',
    'platform_admin.user_suspend': 'users:write',
    'platform_admin.user_activate': 'users:write',
    'platform_admin.user_reset_password': 'users:reset_password',
    'platform_admin.organizations': 'users:read',
    'platform_admin.subscriptions': 'billing:read',
    'platform_admin.billing': 'billing:read',
    'platform_admin.ai_analytics': 'ai:read',
    'platform_admin.ai_providers': 'ai:read',
    'platform_admin.agents': 'ai:read',
    'platform_admin.knowledge': 'ai:read',
    'platform_admin.tools': 'ai:read',
    'platform_admin.storage': 'infra:read',
    'platform_admin.infrastructure': 'infra:read',
    'platform_admin.monitoring': 'infra:read',
    'platform_admin.health_page': 'infra:read',
    'platform_admin.audit': 'audit:read',
    'platform_admin.feature_flags': 'flags:read',  # POST also needs flags:write (checked in view)
    'platform_admin.settings': 'settings:read',
    'platform_admin.section_stub': 'dashboard:read',
    'platform_admin.staff': 'admins:manage',
}
